name = "rpc-proxy" # todo
main = "./src/index.ts"
compatibility_date = "2022-05-03"
compatibility_flags = ["streams_enable_constructors"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
